android.useAndroidX=true
kotlin.mpp.androidGradlePluginCompatibility.nowarn=true

org.jetbrains.compose.experimental.wasm.enabled=true
kotlin.code.style=official
# KMP Web desteği için gerekli deneysel özellikler
org.jetbrains.kotlin.wasm.enabled=true
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
kotlin.daemon.jvmargs=-Xmx3g
